# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondomDistributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(default=b'', max_length=300)),
                ('latitude', models.CharField(default=b'', max_length=300)),
                ('object_id', models.CharField(default=b'', max_length=300)),
                ('site_name', models.CharField(default=b'', max_length=300)),
                ('hours', models.CharField(default=b'', max_length=300)),
                ('address', models.CharField(default=b'', max_length=300)),
                ('city', models.CharField(default=b'', max_length=300)),
                ('state', models.CharField(default=b'', max_length=300)),
                ('zip', models.CharField(default=b'', max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.CreateModel(
            name='HealthyStartCRC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(default=b'', max_length=300)),
                ('latitude', models.CharField(default=b'', max_length=300)),
                ('object_id', models.CharField(default=b'', max_length=300)),
                ('facility_name', models.CharField(default=b'', max_length=300)),
                ('address', models.CharField(default=b'', max_length=300)),
                ('city', models.CharField(default=b'', max_length=300)),
                ('state', models.CharField(default=b'', max_length=300)),
                ('phone', models.CharField(default=b'', max_length=300)),
                ('days_open', models.CharField(default=b'', max_length=300)),
                ('hours', models.CharField(default=b'', max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.CreateModel(
            name='WICOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(default=b'', max_length=300)),
                ('latitude', models.CharField(default=b'', max_length=300)),
                ('object_id', models.CharField(default=b'', max_length=300)),
                ('loc_name', models.CharField(default=b'', max_length=300)),
                ('status', models.CharField(default=b'', max_length=300)),
                ('score', models.CharField(default=b'', max_length=300)),
                ('match_type', models.CharField(default=b'', max_length=300)),
                ('match_addr', models.CharField(default=b'', max_length=300)),
                ('side', models.CharField(default=b'', max_length=300)),
                ('user_fld', models.CharField(default=b'', max_length=300)),
                ('addr_type', models.CharField(default=b'', max_length=300)),
                ('arc_street', models.CharField(default=b'', max_length=300)),
                ('arc_zip', models.CharField(default=b'', max_length=300)),
                ('name', models.CharField(default=b'', max_length=300)),
                ('address', models.CharField(default=b'', max_length=300)),
                ('address_2', models.CharField(default=b'', max_length=300)),
                ('zip', models.CharField(default=b'', max_length=300)),
                ('phone_number', models.CharField(default=b'', max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
    ]
